### ISSUE TITLE
Feature Request - Return of Night Mode 

### ISSUE THREAD

**Issue by lucknaumann** [mirinsoft/CloneApp#1]
Hi,
I've just recently come across your CloneApp and found a video on YouTube from 2015 showing it having a night mode. What happened to this? Please return this feature or even make it similar to CleanMgr+. And if it could also be included in the Settings panel that would be fantastic! =]
https://youtu.be/jbpLGo3dlzE?t=118

**Comment by Belim** [comment]
Currently NOT planned. To much work and to little time.
