### ISSUE TITLE
Command line only opening main window

### ISSUE THREAD

**Issue by robertl87** [mirinsoft/CloneApp#12]
Hi, I'm trying to do a backup from command line option with paramter /auto. I tried:

> CloneApp.exe /auto
> CloneApp.exe /b
> CloneApp.exe -auto

But the only thing it does is opening the main program without starting any backup. What am I doing wrong?

**Comment by Belim** [comment]
Hi,
 `/AUTO` is case-sensitive and should work. More infos on chapter 5.2
https://github.com/builtbybel/CloneApp/blob/master/docs/manual.pdf

**Comment by robertl87** [comment]
Ah, that's it. Thanks!
