### ISSUE TITLE
Does is still work on Windows 11?

### ISSUE THREAD

**Issue by katastrophe92** [mirinsoft/CloneApp#31]
First of all thank you for this repository, I hope is still working. I just found this repo but I used debloat tools from the developer in the past approx. 4 years. Hope someone can answer my question. Thanks!

**Comment by Caskexe** [comment]
I've only ever used it in a Virtual Machine of Windows 11, but it works much the same way as it did for Windows 10 in my experience!

**Comment by mediaexplorer74** [comment]
I cannot find [CloneApp-UA Version to Backup UWP apps](https://github.com/builtbybel/CloneApp-UA) repo. The GitHub-address was builtbybel/CloneApp-UA. Holy shit :(
